### PR TITLE
HTTP Client lib: make request label option mandatory

### PR DESCRIPTION
**Pull request by eduard-fa**
## Changes
Based on our internal discussion, we make requestLabel mandatory to ensure it is always present in our requests.

## Checklist

- [x] Apply one of following labels; `major`, `minor`, `patch` or `skip-release`
- [x] I've updated the documentation, or no changes were necessary
- [ ] I've updated the tests, or no changes were necessary

### CODE REVIEW

**Comment by kibertoad** [comment]
It's a semver major.

**Comment by eduard-fa** [comment]
> It's a semver major.

While it is a breaking change, I'm slightly hesitant to do a major version bump just because of that tiny change. Is it worth it? Could we postpone releasing it until we accrue a few more changes?

**Comment by kibertoad** [comment]
Numbers are cheap. Considering that we are not maintaining a migration guide, I would argue that smaller major releases are likely to be way easier to migrate to.
No strong opinion, though. If you prefer to defer, we can mark as skip-release.

**Comment by kibertoad** [comment]
Let's release this together with https://github.com/lokalise/node-core/pull/90

**Review by kibertoad — APPROVED** [review]

**Pull request merged**
